[advisories]
ignore = [
  "RUSTSEC-2021-0089",
  "RUSTSEC-2020-0077",
]
# warn for categories of informational advisories
informational_warnings = [
    "unmaintained",
    "unsound",
]

[target]
arch = "wasm32"
